name: ValorantPorting Builder

on:
  workflow_dispatch:
    inputs:
        appVersion:
          description: 'ValorantPorting Version And Release Tag'
          required: true
          default: '1.0.X.X'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: GIT Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Fetch Submodules Recursively
        run: git submodule update --init --recursive

      - name: .NET Setup
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            6.0.x
            9.0.x
            10.0.x

      - name: .NET Restore
        run: dotnet restore ValorantPorting

      - name: .NET Publish
        run: dotnet publish ValorantPorting -c Release --no-self-contained -r win-x64 -f net10.0-windows -o "./ValorantPorting/bin/Publish/" -p:PublishReadyToRun=false -p:PublishSingleFile=true -p:DebugType=None -p:GenerateDocumentationFile=false -p:DebugSymbols=false -p:AssemblyVersion=${{ github.event.inputs.appVersion }} -p:FileVersion=${{ github.event.inputs.appVersion }}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ValorantPorting-Build
          path: ./ValorantPorting/bin/Publish/ValorantPorting.exe
